# Introdução às estruturas de dados do Pandas: **Series e DataFrames**

Esses dois são os tipos de estruturas de dados mais usados na ciência de dados. São formas de estruturar dados, a partir dos quais é possível realizar algumas operações.

Veremos como organizar/arranjar/distribuir/escrever/definir listas, dicionários, etc. nos formatos de Series e DataFrame e, em seguida, veremos como operá-las.

## Series

Uma Series é um array com rótulos de 1 dimensão e é capaz de conter qualquer tipo de dado do Python. Os rótulos são chamados de índices (```index```).

O método mais básico de criar uma série no pandas é definindo:

>>```s = pd.Series(data=parametro_com_nome_do_conjunto_de_dados, index = indice)```

O parâmetro ```dados``` pode ser de diferentes tipo:



*   Lista
*   Dicionário
*   ND-Array
*   Valor escalar

O índice é um rótulo/nome para cada linha.

Carregando o Pandas e o NumPy para ilustramos esse conceito para alguns parâmetros diferentes.

In [1]:
import pandas as pd
import numpy as np

### Definindo uma ***Series*** a partir de uma lista

Definindo uma lista a ser usada: a lista de renda por classe social, baseada em dados do IBGE de 2020.

In [2]:
# Seja a lista abaixo

rendas = [20900, 10450, 4180, 2090, 0]
rendas

[20900, 10450, 4180, 2090, 0]

Definindo a Series:

In [5]:
classeSocialSemIndex = pd.Series(data = rendas)
classeSocialSemIndex

0    20900
1    10450
2     4180
3     2090
4        0
dtype: int64

Note que passamos apenas o primeiro parâmetro, o *data*, de modo que só foi criada uma coluna com os dados e a coluna mais à esquerda tem números (índices) automáticos.

Agora caso queiramos da rótulos para cada linha de uma forma particular, vamos precisar passas os índices. Para indicar ínices de uma forma desejada, podemos **passar o segundo parâmetro**:

In [6]:
indices = ['A', 'B', 'C', 'D', 'E']

# já criando a Series com índice

classeSocialComIndex = pd.Series(data = rendas, index = indices)
classeSocialComIndex

A    20900
B    10450
C     4180
D     2090
E        0
dtype: int64

#### Acessando os valores de uma Series

Acessando valores de uma Series sem index

In [12]:
classeSocialSemIndex[0]

np.int64(20900)

In [7]:
classeSocialSemIndex[2]

np.int64(4180)

In [14]:
classeSocialSemIndex[len(rendas)-1]

np.int64(0)

Acessando valores de uma Series com index: acesso via rótulo

In [13]:
classeSocialComIndex['B']

np.int64(10450)

In [15]:
classeSocialComIndex['E']

np.int64(0)

Uma forma de fazer uma consulta rápida dos índices é:

In [16]:
classeSocialComIndex.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

Uma forma de acessa em partes:

In [17]:
classeSocialComIndex['B':'D']

B    10450
C     4180
D     2090
dtype: int64

In [18]:
classeSocialSemIndex[0:len(rendas)]

0    20900
1    10450
2     4180
3     2090
4        0
dtype: int64

Podemos ainda mudar os índices das Series. Vamos trocar os valores da lista indices:

In [19]:
# indices = ['A', 'B', 'C', 'D', 'E']

indices = [10, 8, 32, 54, 178]

classeSocialComIndex = pd.Series(data = rendas, index = indices)
classeSocialComIndex

10     20900
8      10450
32      4180
54      2090
178        0
dtype: int64

Acessando os valores:

In [20]:
classeSocialComIndex[10]

np.int64(20900)

Podemos fazer essa mesma troca de índices sem precisar criar a Series novemente, mas, em vez disso, só reatribuindo os índices como segue (para ilustrar, vou trocar só os índices novamente):

In [25]:
indices = [47, 8, 131, 1,0.5]

#classeSocialComIndex.index = indices

In [27]:
classeSocialComIndex.index = indices
classeSocialComIndex

47.0     20900
8.0      10450
131.0     4180
1.0       2090
0.5          0
dtype: int64

In [28]:
# acessando

classeSocialComIndex[47]

np.int64(20900)

### Definindo uma ***Series*** a partir de um dicionário

Criando o dicionário:

In [29]:
# criando o dicionário

classeSocialDicionario = { 'A': 20900, 'B': 10450, 'C': 4180, 'D': 2090, 'E': 0
}

Criando a Series sem indice.

In [30]:
classeDicionarioSemIndex = pd.Series(data = classeSocialDicionario)
classeDicionarioSemIndex

A    20900
B    10450
C     4180
D     2090
E        0
dtype: int64

### Definindo uma ***Series*** a partir de um ND-Array

In [33]:
array_aleatorio = np.random.randn(5)

In [34]:
pd.Series(array_aleatorio)

0    1.164581
1    0.809651
2    0.421697
3   -0.784094
4    1.048007
dtype: float64

### Definindo uma ***Series*** a partir de um escalar

In [36]:
pd.Series(4, index = indices)

8    4
6    4
4    4
2    4
0    4
dtype: int64


-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------



## DataFrame

É uma estrutura de dados com rótulos de 2 dimensões, podendo ter colunas de diferentes tipos. É comparável às tabelas do excel ou de banco de dados. É a estrutura do Pandas mais usada.

### Definindo um ***DataFrame*** a partir de uma lista

In [38]:
# definindo a lista

lista_df = [2, 4, 6, 8, 10]

In [42]:
# definindo o DataFrame
# cada coluna é como uma Series

pd.DataFrame(lista_df)

    0
0   2
1   4
2   6
3   8
4  10

In [43]:
# renomenado a coluna

pd.DataFrame(lista_df, columns = ['Pares'])

   Pares
0      2
1      4
2      6
3      8
4     10

### Definindo um ***DataFrame*** a partir de um dicionário

In [45]:
# definindo o df

pd.DataFrame({'Ímpares': [1, 3, 5, 7, 9]})
# o nome da coluna é uma chave; o valor é uma lista

   Ímpares
0        1
1        3
2        5
3        7
4        9

### Definindo um ***DataFrame*** a partir de um dicionário com 2 listas

In [46]:
pd.DataFrame( { 'pares': [2, 4, 6, 8, 10],
               'ímpares': [1, 3, 5, 7, 9]
}
)

   pares  ímpares
0      2        1
1      4        3
2      6        5
3      8        7
4     10        9

### Definindo um ***DataFrame*** a partir de uma Series do Pandas

Vou criar uma tabela com a população e área de alguns estados brasileiros.

In [47]:
popBrasilDicionario = {'Amazonas': 3938336, 'São Paulo': 44396484, 'Bahia': 15203934}
areaBrasilDicionario = {'Amazonas': 1571825, 'São Paulo': 248219, 'Bahia': 564760}

In [48]:
popBrasilDicionario

{'Amazonas': 3938336, 'São Paulo': 44396484, 'Bahia': 15203934}

In [49]:
areaBrasilDicionario

{'Amazonas': 1571825, 'São Paulo': 248219, 'Bahia': 564760}

Criando as 2 Series com esses dicionários:

In [55]:
populacaoSeries = pd.Series(popBrasilDicionario)
populacaoSeries

Amazonas      3938336
São Paulo    44396484
Bahia        15203934
dtype: int64

In [56]:
areaSeries = pd.Series(areaBrasilDicionario)
areaSeries

Amazonas     1571825
São Paulo     248219
Bahia         564760
dtype: int64

  Criando o DataFrame, para isso, vou passar um dicionário para o Dataframe sendo que a chave é o cabeçalho da coluna e o valor sá as Series que criei com os valores de População e Área:

In [57]:
estadosBrasil = pd.DataFrame( {'População': populacaoSeries, 'Área': areaSeries})
estadosBrasil

           População     Área
Amazonas     3938336  1571825
São Paulo   44396484   248219
Bahia       15203934   564760

## Operações com DataFrame

### Acessando elementos: ```.loc``` e ```.iloc```

É possível acessar de 2 formas;



*   .loc - acessa por rótulo (nome do índice)
*   .iloc - acessa por posição numérica (0, 1, 2, ...)

As contagens dos índices são na seguinte ordem:



*   0: População
*   1: Área

In [66]:
## acessando por .loc - rótulo/nome do índice
estadosBrasil.loc['São Paulo', 'Área']

np.int64(248219)

Aqui é preciso ter cuidado, porque a matriz de dados é do tipo 3x2, de modo que:


*   00 é a Pop. de AM e 01 é a Área de AM;
*   10 é a Pop. de SP e 11 é a Área de SP;
*   20 é a Pop. de BA e 21 é a Área de BA.

In [74]:
### acessarndo por .iloc- por posição numérica
estadosBrasil.iloc[1, 1]

np.int64(248219)

### Acessando colunas

In [62]:
estadosBrasil['População']

Amazonas      3938336
São Paulo    44396484
Bahia        15203934
Name: População, dtype: int64

In [64]:
estadosBrasil['Área']

Amazonas     1571825
São Paulo     248219
Bahia         564760
Name: Área, dtype: int64

### Soma vertical

Caso queiramos somar os valores de uma coluna:

In [60]:
estadosBrasil['Área'].sum()

np.int64(2384804)

### Criando uma nova coluna

In [61]:
estadosBrasil['Densidade'] = estadosBrasil['População'] / estadosBrasil['Área']
estadosBrasil

           População     Área   Densidade
Amazonas     3938336  1571825    2.505582
São Paulo   44396484   248219  178.860136
Bahia       15203934   564760   26.921053

### Soma horizontal (só por curiosidade)

Uma soma dos elementos da linha aqui não faz sentido porque estaremos somando população com área. Vou mostrar aqui só para mostrar a possibilidade.

Para fazer a soma, basta adicionar o parâmetro axis=1, pois axis=0 indica a soma por coluna (padrão).

In [77]:
estadosBrasil.sum(axis=1).astype(int) # adicionei .astype(int) para não ficar em notação científica

Amazonas      5510163
São Paulo    44644881
Bahia        15768720
dtype: int64

Outra maneira de escrever essa soma para não ficar em notação científica:

In [76]:
pd.options.display.float_format = '{:.0f}'.format
estadosBrasil.sum(axis=1)

Amazonas     5510164
São Paulo   44644882
Bahia       15768721
dtype: float64