Estruturas de dados do Pandas

# **Objetos Index**: Indexação, Seleção e Filtragem

Vamos ver um pouco mais sobre indexação, como selecionar (acessar) valores e/ou colunas e a filtrar.

Para fazer esses processos, seguimos a anatomia listada no quadro abaixo.

|Operação                                    | Sintaxe             | Resultado    |
|:---------:                                 |:-------------------:|:------------:|
|Seleciona uma coluna                        | ``df[col]``         | ``Series``   |
|Seleciona duas colunas                      | ``df[[col1, col2]]``| ``DataFrame``|
|Seleciona uma linha usando rótulo           | ``df.loc[rotulo]``  | ``Series``   |
|Seleciona uma linha usando inteiro          | ``df.iloc[i]``      | ``Series``   |
|Recorta o dataframe da linha 2 a 5          | ``df[2:5]``        |``DataFrame`` |
|Seleciona linhas usando um vetor booleano   | ``df[vetor_bool]``    | ``DataFrame``|

Para vermos como essas operações se aplicam, vamos usar os mesmos dados usado na aula anterior. Vamos definir de novo Series e Daframe a partir de um dicionário.

In [1]:
import pandas as pd
import numpy as np

In [2]:
popBrasilDicionario = {'Amazonas': 3938336, 'São Paulo': 44396484, 'Bahia': 15203934, 'Minas Gerais': 20869101, 'Roraima': 505665, 'Distrito Federal': 2914830}
areaBrasilDicionario = {'Amazonas': 1571825, 'São Paulo': 248219, 'Bahia': 564760, 'Minas Gerais': 869101, 'Roraima': 45665, 'Distrito Federal': 4830}

Criando uma Series:

In [3]:
populacaoSeries = pd.Series(popBrasilDicionario)

In [4]:
areaSeries = pd.Series(areaBrasilDicionario)

Criando um DataFrame:

In [5]:
estadosBrasil = pd.DataFrame( {'População': populacaoSeries, 'Área': areaSeries})
estadosBrasil

                  População     Área
Amazonas            3938336  1571825
São Paulo          44396484   248219
Bahia              15203934   564760
Minas Gerais       20869101   869101
Roraima              505665    45665
Distrito Federal    2914830     4830

Vou só adicionar mais uma coluna, a de Densidade.

In [9]:
estadosBrasil['Densidade'] = estadosBrasil['População'] / estadosBrasil['Área']
estadosBrasil

                  População     Área   Densidade
Amazonas            3938336  1571825    2.505582
São Paulo          44396484   248219  178.860136
Bahia              15203934   564760   26.921053
Minas Gerais       20869101   869101   24.012285
Roraima              505665    45665   11.073360
Distrito Federal    2914830     4830  603.484472

### Selecionando uma coluna

O retorno vai ser uma Series.

In [10]:
estadosBrasil['População']

Amazonas             3938336
São Paulo           44396484
Bahia               15203934
Minas Gerais        20869101
Roraima               505665
Distrito Federal     2914830
Name: População, dtype: int64

In [11]:
estadosBrasil['Área']

Amazonas            1571825
São Paulo            248219
Bahia                564760
Minas Gerais         869101
Roraima               45665
Distrito Federal       4830
Name: Área, dtype: int64

In [12]:
# é possível acessar só com . e o nome da coluna
# ATENÇÃO!!!!
# Se o nome da coluna for composto (formado por mais de uma palavra), esse método NÃO vai funcionar

estadosBrasil.Área

Amazonas            1571825
São Paulo            248219
Bahia                564760
Minas Gerais         869101
Roraima               45665
Distrito Federal       4830
Name: Área, dtype: int64

## Selecionando duas colunas

O retorno vai ser um DataFrame.

In [14]:
estadosBrasil[['População', 'Área']] # sempre usar 2 colchetes concêntricos

                  População     Área
Amazonas            3938336  1571825
São Paulo          44396484   248219
Bahia              15203934   564760
Minas Gerais       20869101   869101
Roraima              505665    45665
Distrito Federal    2914830     4830

### Selecionando duas colunas e invertendo a ordem

In [15]:
estadosBrasil[['Área', 'População']]

                     Área  População
Amazonas          1571825    3938336
São Paulo          248219   44396484
Bahia              564760   15203934
Minas Gerais       869101   20869101
Roraima             45665     505665
Distrito Federal     4830    2914830

## .loc: Selecionando uma linha usando o rótulo/'nome'

O retorno vai ser uma Series.

In [17]:
estadosBrasil.loc['Minas Gerais']

População    2.086910e+07
Área         8.691010e+05
Densidade    2.401229e+01
Name: Minas Gerais, dtype: float64

Retornou em notação científica.

## Selecionando uma linha usando o índice

Retorna uma Series, assim como o .loc.

|índice                                    | Coluna 0             | Coluna 1    |
|:---------:                                 |:-------------------:|:------------:|
|Índice 1                        | 00         | 01   |
|Índice 2                      | 10 | 11 |
|Índice 3          | 20  | 21   |

No nosso exemplo:

|Estado     | População | Área    | Densidade |
|:---------: |:-------------------:|:------------:| :------------:|
|Amazonas      | 00   | 01   |  |
|São Paulo     | 10 | 11 |  |
|Bahia     | 20  | 21   |  |
|Minas     | 20  | 21   |  |
|Roraima     | 20  | 21   |  |
|Distrito Federal     | 20  | 21   |  |

In [18]:
# vai puxar todos os dados da 4ª linha

estadosBrasil.iloc[3]

População    2.086910e+07
Área         8.691010e+05
Densidade    2.401229e+01
Name: Minas Gerais, dtype: float64

## 'Fatiando' o dataframe a partir de alguns nomes: Slicing

In [19]:
estadosBrasil['Bahia': 'Roraima']

              População    Área  Densidade
Bahia          15203934  564760  26.921053
Minas Gerais   20869101  869101  24.012285
Roraima          505665   45665  11.073360

### Filtrando o DataFrame com vetor booleano

O retorno será um DataFrame.

Aqui o objetivo é definir uma avaliação booleana e, a partir dela, retornar um vetor ou conjunto de valores booleanos. O objetivo não é só retornar um booleano com esses valores, mas surge como uma possibilidade de usar esse caminho para obter outros resultados, como o exemplo abaixo.

In [21]:
vetor_booleano = estadosBrasil['Área'] > 50000
vetor_booleano

Amazonas             True
São Paulo            True
Bahia                True
Minas Gerais         True
Roraima             False
Distrito Federal    False
Name: Área, dtype: bool

Obtivemos o valor tipo bool no vetor_booleano.

Mas o objetivo é poder usar isso de outras forma, como no exemplo abaixo em que obtemos um DataFrame a partir de um bool.

In [22]:
estadosBrasil[vetor_booleano]

              População     Área   Densidade
Amazonas        3938336  1571825    2.505582
São Paulo      44396484   248219  178.860136
Bahia          15203934   564760   26.921053
Minas Gerais   20869101   869101   24.012285

## Transpondo o dataframe

Basta adicionar .T

In [23]:
estadosBrasil.T

,Amazonas,São Paulo,Bahia,Minas Gerais,Roraima,Distrito Federal
População,3.938336e+06,4.439648e+07,1.520393e+07,2.086910e+07,505665.00000,2.914830e+06
Área,1.571825e+06,2.482190e+05,5.647600e+05,8.691010e+05,45665.00000,4.830000e+03
Densidade,2.505582e+00,1.788601e+02,2.692105e+01,2.401229e+01,11.07336,6.034845e+02

Note que nesse exemplo e em outros obtivemos os números em notação científica.

Para evitar isso, podemos usar o seguinte comando:

In [24]:
pd.options.display.float_format = '{:.2f}'.format

In [25]:
estadosBrasil.T

,Amazonas,São Paulo,Bahia,Minas Gerais,Roraima,Distrito Federal
População,3938336.00,44396484.00,15203934.00,20869101.00,505665.00,2914830.00
Área,1571825.00,248219.00,564760.00,869101.00,45665.00,4830.00
Densidade,2.51,178.86,26.92,24.01,11.07,603.48

## Acessando os valores do DataFrame usando ``values``

Vai retornar um array.

In [26]:
estadosBrasil.values

array([[3.93833600e+06, 1.57182500e+06, 2.50558173e+00],
       [4.43964840e+07, 2.48219000e+05, 1.78860136e+02],
       [1.52039340e+07, 5.64760000e+05, 2.69210532e+01],
       [2.08691010e+07, 8.69101000e+05, 2.40122851e+01],
       [5.05665000e+05, 4.56650000e+04, 1.10733603e+01],
       [2.91483000e+06, 4.83000000e+03, 6.03484472e+02]])

Para acessar apenas os valores da linha 0:

In [27]:
estadosBrasil.values[0]

array([3.93833600e+06, 1.57182500e+06, 2.50558173e+00])

In [28]:
estadosBrasil.values[1]

array([4.43964840e+07, 2.48219000e+05, 1.78860136e+02])

## Acessando os valores do DataFrame usando ``loc`` com condições

In [29]:
estadosBrasil.loc[estadosBrasil['Densidade'] < 10 ]

          População     Área  Densidade
Amazonas    3938336  1571825       2.51

In [30]:
# Aqui não retorna a linha, mas apenas a Densidade

estadosBrasil.loc[estadosBrasil['Densidade'] < 10, 'Densidade' ]

Amazonas   2.51
Name: Densidade, dtype: float64

### Substituindo um valor

Agora que selecionamos os estados em que a Densidade é menor que 10, podemos substituir o valor da densidade por outro, por exemplo, por 90000.

In [31]:
estadosBrasil.loc[estadosBrasil['Densidade'] < 10, 'Densidade'] = 90000

Verificando como está agoira:

In [32]:
estadosBrasil

                  População     Área  Densidade
Amazonas            3938336  1571825   90000.00
São Paulo          44396484   248219     178.86
Bahia              15203934   564760      26.92
Minas Gerais       20869101   869101      24.01
Roraima              505665    45665      11.07
Distrito Federal    2914830     4830     603.48

## Acessando os valores do DataFrame usando ``iloc``

In [34]:
estadosBrasil

                  População     Área  Densidade
Amazonas            3938336  1571825   90000.00
São Paulo          44396484   248219     178.86
Bahia              15203934   564760      26.92
Minas Gerais       20869101   869101      24.01
Roraima              505665    45665      11.07
Distrito Federal    2914830     4830     603.48

In [33]:
estadosBrasil.iloc[2]

População   15203934.00
Área          564760.00
Densidade         26.92
Name: Bahia, dtype: float64

Acessando só a Densidade desse estado.

In [35]:
estadosBrasil.iloc[2,2]

np.float64(26.921053190735886)

Agora se quisermos trocar o valor da Densidade desse estado, seguimos como abaixo.

In [36]:
estadosBrasil.iloc[2,2] = 100000

In [37]:
estadosBrasil

                  População     Área  Densidade
Amazonas            3938336  1571825   90000.00
São Paulo          44396484   248219     178.86
Bahia              15203934   564760  100000.00
Minas Gerais       20869101   869101      24.01
Roraima              505665    45665      11.07
Distrito Federal    2914830     4830     603.48